# ####################################################################

#  Created by Genus(TM) Synthesis Solution 25.12-s067_1 on Mon Mar 23 21:15:23 UTC 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1fF
set_units -time 1000ps

# Set the current design
current_design biriscv_multiplier

create_clock -name "clk" -period 10.0 -waveform {0.0 5.0} [get_ports clk_i]
set_false_path -from [get_ports rst_i]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports opcode_valid_i]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_opcode_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_pc_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports opcode_invalid_i]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rd_idx_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rd_idx_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rd_idx_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rd_idx_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rd_idx_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_idx_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_idx_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_idx_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_idx_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_idx_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_idx_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_idx_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_idx_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_idx_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_idx_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_ra_operand_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {opcode_rb_operand_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports hold_i]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {writeback_value_o[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.05 [get_clocks clk]
set_clock_uncertainty -hold 0.05 [get_clocks clk]
